In [8]:
import pandas as pd 
import numpy as np 

df = pd.read_csv('mdf7.csv')

In [9]:


df.rename(columns={'updated_wins': 'constructors_wins', 'updated_poles': 'constructors_poles'}, inplace=True)

races = df[['season', 'circuit_id', 'round']].drop_duplicates().values

for race in races:
    season, circuit, rnd = race
    winning_constructor = df[(df['season'] == season) & 
                             (df['circuit_id'] == circuit) & 
                             (df['round'] == rnd) & 
                             (df['Rank'] == 1)]['constructor_id'].values[0]
    pole_constructor = df[(df['season'] == season) & 
                          (df['circuit_id'] == circuit) & 
                          (df['round'] == rnd) & 
                          (df['grid'] == 1)]['constructor_id'].values[0]
    df.loc[(df['season'] == season) & 
           (df['circuit_id'] == circuit) & 
           (df['round'] == rnd) & 
           (df['constructor_id'] == winning_constructor), 
           'constructors_wins'] -=1
    df.loc[(df['season'] == season) & 
           (df['circuit_id'] == circuit) & 
           (df['round'] == rnd) & 
           (df['constructor_id'] == pole_constructor), 
           'constructors_poles'] -= 1

df.loc[df['Rank'] == 1, ['updated_driver_wins']] -= 1
df.loc[df['grid'] == 1, ['updated_driver_poles']] -= 1

In [10]:
columns_to_encode = ['driver_id','circuit_id','grid', 'constructor_id', 'configuration', 'drs_zones', 'Engine Manufacturer']

# One-hot encode the specified columns
df1 = pd.get_dummies(df, columns=columns_to_encode)

df1.rename(columns={'updated_driver_wins': 'driver_wins', 'updated_driver_poles': 'driver_poles'}, inplace=True)

df1 = df1[df1['Finished'] != 0]

df1.drop(['Finished','Points','circuit_country','year_of_birth', 'Laps', 'constructor_country_of_origin','driver_country_of_origin',
         'Engine', 'Displacement', 'Cylinders', 'Valves'], axis = 1, inplace = True)

In [11]:
df1.to_csv('df1.csv', index = False)

In [12]:
df1[(df1['season'] == 2013) &(df1['round'] == 9)]

,season,Rank,round,Points Before GP,constructors_wins,constructors_poles,height (cm),weight (kg),driver_wins,driver_poles,...,drs_zones_1,drs_zones_2,drs_zones_3,drs_zones_4,Engine Manufacturer_Cosworth,Engine Manufacturer_Ferrari,Engine Manufacturer_Honda,Engine Manufacturer_Honda RBPT,Engine Manufacturer_Mercedes,Engine Manufacturer_Renault
1515,2013,1,9,132.0,37,49,176,58,29,39,...,0,1,0,0,0,0,0,0,0,1
1516,2013,2,9,98.0,2,0,175,62,21,16,...,0,1,0,0,0,0,0,0,0,1
1517,2013,3,9,26.0,2,0,180,71,0,0,...,0,1,0,0,0,0,0,0,0,1
1518,2013,4,9,111.0,221,207,171,68,32,22,...,0,1,0,0,0,1,0,0,0,0
1519,2013,5,9,89.0,12,14,175,66,21,28,...,0,1,0,0,0,0,0,0,1,0
1520,2013,6,9,25.0,182,155,182,72,15,8,...,0,1,0,0,0,0,0,0,1,0
1521,2013,7,9,87.0,37,49,185,75,9,11,...,0,1,0,0,0,0,0,0,0,1
1522,2013,8,9,12.0,182,155,173,63,0,0,...,0,1,0,0,0,0,0,0,1,0
1523,2013,9,9,82.0,12,14,178,71,3,4,...,0,1,0,0,0,0,0,0,1,0
1524,2013,10,9,6.0,1,1,184,70,0,1,...,0,1,0,0,0,1,0,0,0,0
1525,2013,11,9,36.0,0,1,185,74,0,0,...,0,1,0,0,0,0,0,0,1,0
1526,2013,12,9,11.0,1,1,175,64,0,0,...,0,1,0,0,0,1,0,0,0,0
1527,2013,13,9,23.0,0,1,183,75,0,0,...,0,1,0,0,0,0,0,0,1,0
1528,2013,14,9,0.0,1,1,180,61,0,0,...,0,1,0,0,0,1,0,0,0,0
1529,2013,15,9,0.0,114,127,173,63,1,1,...,0,1,0,0,0,0,0,0,0,1
1530,2013,16,9,0.0,114,127,173,70,0,0,...,0,1,0,0,0,0,0,0,0,1
1531,2013,17,9,0.0,210,203,178,60,0,0,...,0,1,0,0,0,0,0,0,0,1
1532,2013,18,9,0.0,210,203,182,73,0,0,...,0,1,0,0,0,0,0,0,0,1
1533,2013,19,9,0.0,0,0,181,64,0,0,...,0,1,0,0,1,0,0,0,0,0